load_balancer:
    image: nginx
    links:
        - web
    ports:
        - "80:80"

cache:
    image: redis

database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=SuperSecretPassword123
        - MYSQL_DATABASE=laravel

web:
    image: webdevops/php-nginx:7.1
    links:
        - database
        - cache
    volumes:
        - ./:/app
    environment:
        - APP_ENV=production
        - DB_DATABASE=laravel
        - DB_PASSWORD=SuperSecretPassword123
        - WEB_DOCUMENT_ROOT=/app/public
